export const GRAMMAR_UI_LABELS = {
  // Human Readable Keys
  "Article Usage": "A, An, The (Articles)",
  "Countability & Plurals": "Singular & Plural Nouns",
  "Pronoun Reference": "Pronouns",
  "Prepositional Accuracy": "Prepositions",
  "Word Forms": "Word Types",
  "Subject-Verb Agreement": "Subject & Verb Matching",
  "Tense Consistency": "Keeping the Same Time",
  "Present Perfect vs. Past Simple": "Past vs. Present Perfect",
  "Gerunds vs. Infinitives": "Verbs with '-ing' or 'to'",
  "Passive Voice Construction": "Passive Voice",
  "Sentence Boundaries": "Complete Sentences",
  "Sentence Boundaries (Fragments/Comma Splices)": "Complete Sentences",
  "Relative Clauses": "Adding Detail (who, which, that)",
  "Subordination": "Joining Sentences",
  "Word Order": "Word Order",
  "Parallel Structure": "Matching Sentence Patterns",
  "Transitional Devices": "Linking Words",
  "Collocations": "Common Word Pairs",
  "Academic Register": "Formal Writing",
  "Nominalization": "Making Verbs into Nouns",
  "Hedging": "Softening Your Language",

  // Snake Case Variants (often returned by API/DB)
  "article_usage": "A, An, The (Articles)",
  "countability_plurals": "Singular & Plural Nouns",
  "pronoun_reference": "Pronouns",
  "prepositional_accuracy": "Prepositions",
  "word_forms": "Word Types",
  "subject_verb_agreement": "Subject & Verb Matching",
  "tense_consistency": "Keeping the Same Time",
  "present_perfect_past_simple": "Past vs. Present Perfect",
  "gerunds_infinitives": "Verbs with '-ing' or 'to'",
  "passive_voice": "Passive Voice",
  "sentence_boundaries": "Complete Sentences",
  "relative_clauses": "Adding Detail (who, which, that)",
  "subordination": "Joining Sentences",
  "word_order": "Word Order",
  "parallel_structure": "Matching Sentence Patterns",
  "transitional_devices": "Linking Words",
  "collocations": "Common Word Pairs",
  "academic_register": "Formal Writing",
  "nominalization": "Making Verbs into Nouns",
  "hedging": "Softening Your Language"
};
